---
namespace: xploit9999
name: utilidades
version: 1.0.1
readme: README.md
authors:
  - John <@Xploit9999>
description: Colección personal sobre necesidades del día a día de automatización en mi trabajo.
license:
  - MIT 
tags:
  - excel
  - graphics
  - openssl
  - linux
  - development
dependencies: {}
repository: https://github.com/Xploit9999/ansible-collection-utilidades
documentation: https://github.com/Xploit9999/ansible-collection-utilidades/blob/master/README.md
issues: https://github.com/Xploit9999/ansible-collection-utilidades/issues
build_ignore:
  - '*.tar.gz'
  - '*.log'
  - __pycache__
  - .cache
  - .DS_Store
  - .git
  - .github
  - .gitignore
  - .python-version
  - .pytest_cache
...
