---
- name: Google Drive | Eliminar | Encontrar archivo a eliminar para obtener su ID
  uri:
    url: "https://www.googleapis.com/drive/v3/files?q=name='{{ archivo | urlencode }}'"
    method: GET
    headers:
      Authorization: "Bearer {{ access_token }}"
    return_content: true
  register: info

- set_fact:
    archivo_id: "{{ info.json.files | map(attribute='id') }}"

- name: Google Drive | Eliminar | Pausa para confirmación de usuario en caso de que se encuentren multiples ids asociadas a un archivo.
  pause:
    prompt: "Se encontraron varios ids asociados al archivo a eliminar, probablemente este repetivo el archivo en su Drive. Desea continuar? (CTRL + C Y C para continuar.)"
  when: archivo_id | length > 1

- name: Google Drive | Eliminar | Se realiza eliminación del archivo
  uri:
    url: "https://www.googleapis.com/drive/v3/files/{{ item }}"
    method: DELETE
    headers:
      Authorization: "Bearer {{ access_token }}"
    status_code: 204
  loop: "{{ archivo_id }}"
  changed_when: true
  no_log: false
  ignore_errors: true
  register: ejecucion

- name: Google Drive | Eliminar | Mensaje de confirmación del archivo eliminado
  debug:
    msg: "El archivo {{ archivo }} se ha eliminado satisfactoriamente"
  when: ejecucion | bool

- name: Google Drive | Error controlado si se detecta que no tiene permisos para eliminar el archivo
  fail:
    msg: "No se puede eliminar el archivo {{ archivo }} por falta de permisos"
  when: ejecucion.results | map(attribute='status') | join | int == 403
...
