---
# handlers file for Google_Drive
- name: Google Drive | Subida | Sube los archivos
  uri:
    url: "https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart"
    method: POST
    headers:
      Authorization: "Bearer {{ access_token }}"
      Content-Type: multipart/related; boundary="EOF"
    body: |
      --EOF
      Content-Type: application/json; charset=UTF-8

      {
        "name": "{{ item | basename }}"
      }

      --EOF
      Content-Type: "{{ lookup('pipe', 'file --mime-type -b ' ~ item) }}"

      {{ lookup('file', item) }}

      --EOF--
    status_code: 200
    return_content: true
  register: subida
  changed_when: true
  no_log: true
  loop: "{{ archivos_validados }}"
...
